/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DomainDomainImport } from './routes/domain/$domain'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DomainDomainRoute = DomainDomainImport.update({
  id: '/domain/$domain',
  path: '/domain/$domain',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/domain/$domain': {
      id: '/domain/$domain'
      path: '/domain/$domain'
      fullPath: '/domain/$domain'
      preLoaderRoute: typeof DomainDomainImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domain/$domain': typeof DomainDomainRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domain/$domain': typeof DomainDomainRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/domain/$domain': typeof DomainDomainRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/domain/$domain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/domain/$domain'
  id: '__root__' | '/' | '/domain/$domain'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainDomainRoute: typeof DomainDomainRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainDomainRoute: DomainDomainRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/domain/$domain"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/domain/$domain": {
      "filePath": "domain/$domain.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
