#!/usr/bin/env node
/**
 * Build-time script to generate CSS manifest from Vite's build output.
 * This reads the manifest.json and extracts CSS file references for the root route.
 */
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const manifestPath = join(rootDir, 'dist', '_build', '.vite', 'manifest.json');
const outputPath = join(rootDir, 'app', 'css-manifest.gen.ts');

try {
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));

  // Find the client entry point
  const clientEntry = Object.entries(manifest).find(
    ([key, value]: [string, any]) =>
      key.includes('client') &&
      value.name === 'client' &&
      value.css
  );

  if (!clientEntry) {
    console.warn('⚠️ No client entry with CSS found in manifest');
    writeFileSync(
      outputPath,
      `// Auto-generated by scripts/generate-css-manifest.ts\nexport const cssManifest: string[] = [];\n`
    );
    process.exit(0);
  }

  const [, entry] = clientEntry;
  const cssFiles = entry.css || [];

  const code = `// Auto-generated by scripts/generate-css-manifest.ts\n// Do not edit manually - run 'bun run build' to regenerate\n\nexport const cssManifest: string[] = ${JSON.stringify(cssFiles, null, 2)};\n`;

  writeFileSync(outputPath, code);
  console.log(`✅ Generated CSS manifest with ${cssFiles.length} file(s):`);
  cssFiles.forEach((css: string) => console.log(`   - ${css}`));
} catch (error) {
  console.error('❌ Failed to generate CSS manifest:', error);
  process.exit(1);
}
